apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generateName: prometheus-
  namespace: tomcat-prometheus
spec:
  source: rh-operators
  name: prometheus
  startingCSV: prometheusoperator.0.22.2
  channel: preview
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: server-instance
  labels:
    prometheus: k8s
  namespace: tomcat-prometheus
spec:
  replicas: 2
  version: v2.3.2
  serviceAccountName: prometheus-k8s
  securityContext: {}
  serviceMonitorSelector:
    matchExpressions:
      - key: k8s-app
        operator: Exists
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: k8s
  alerting:
    alertmanagers:
      - namespace: monitoring
        name: alertmanager-main
        port: web
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  labels:
    operated-prometheus: 'true'
  name: prometheus-operated
  namespace: tomcat-prometheus
spec:
  host: prometheus-operated-tomcat-prometheus.router.default.svc.cluster.local
  port:
    targetPort: web
  to:
    kind: Service
    name: prometheus-operated
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - host: prometheus-operated-tomcat-prometheus.router.default.svc.cluster.local
    routerName: router
    wildcardPolicy: None
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tomcat-server
  labels:
    k8s-app: prometheus
  namespace: tomcat-prometheus
spec:
  selector:
    matchLabels:
      app: tomcat-prometheus
  endpoints:
    - port: web
      interval: 30s